version: 2

project_name: smart-git-proxy

builds:
  - main: ./cmd/proxy
    binary: smart-git-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
    ignore:
      - goos: darwin
        goarch: amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - id: deb
    package_name: smart-git-proxy
    vendor: RunsOn
    homepage: https://github.com/runs-on/smart-git-proxy
    maintainer: Cyril Rohr <hey@cyrilrohr.com>
    description: HTTP smart Git mirror proxy for git fetch/clone
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: scripts/smart-git-proxy.service
        dst: /lib/systemd/system/smart-git-proxy.service
      - src: scripts/env.example
        dst: /etc/smart-git-proxy/env
        type: config|noreplace
    scripts:
      preinstall: scripts/preinstall.sh
      postinstall: scripts/postinstall.sh
      preremove: scripts/preremove.sh
      postremove: scripts/postremove.sh

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: runs-on
    name: smart-git-proxy
