AWSTemplateFormatVersion: '2010-09-09'
Description: Smart Git Proxy with auto-discovery via Route53 private hosted zone

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Main configuration [required]"
        Parameters:
          - VpcId
          - SubnetIds
          - ClientSecurityGroupId
          - InstanceType
          - RootVolumeSize

Mappings:
  Config:
    Proxy:
      Version: "0.2.5"

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC to deploy into
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for the ASG (private subnets recommended)
  ClientSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group of clients that will access the proxy
  AssignPublicIp:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: Assign public IP (set to true for public subnets)
  InstanceType:
    Type: String
    Default: m8gd.large
    AllowedPattern: ^[a-z][0-9]+g[a-z]*\.[a-z0-9]+$
    ConstraintDescription: Must be a Graviton instance type (e.g., t4g.micro, c7gd.large, m7g.medium).
    Description: EC2 instance type (use m8gd for ARM with NVMe instance store). If many parallel clones are expected, use a larger instance type with more CPU and memory.
  RootVolumeSize:
    Type: Number
    Default: 30
    Description: Root EBS volume size in GB

Conditions:
  UsePublicIp: !Equals [!Ref AssignPublicIp, "true"]

Resources:
  # Private hosted zone for DNS-based service discovery
  PrivateHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: runs-on.internal
      VPCs:
        - VPCId: !Ref VpcId
          VPCRegion: !Ref AWS::Region
      HostedZoneConfig:
        Comment: !Sub Smart Git Proxy private zone for ${AWS::StackName}

  # Security group for the proxy
  # Note: For SSM access in private subnets, ensure VPC has either:
  # - NAT Gateway, or
  # - VPC endpoints for: ssm, ssmmessages, ec2messages
  ProxySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Smart Git Proxy
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ClientSecurityGroupId
          Description: Git proxy from clients
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS for SSM, GitHub, package downloads
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP for package repos

  # IAM role for EC2 instances
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: Route53Registration
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - route53:ChangeResourceRecordSets
                Resource: !Sub arn:aws:route53:::hostedzone/${PrivateHostedZone}
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:DeleteParameter
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/smart-git-proxy/instances/*
              - Effect: Allow
                Action:
                  - autoscaling:CompleteLifecycleAction
                Resource: '*'

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  # Launch template
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64}}'
        InstanceType: !Ref InstanceType
        IamInstanceProfile:
          Arn: !GetAtt InstanceProfile.Arn
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: !If [UsePublicIp, true, false]
            Groups:
              - !Ref ProxySecurityGroup
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: !Ref RootVolumeSize
              VolumeType: gp3
              DeleteOnTermination: true
        MetadataOptions:
          HttpTokens: required
          HttpEndpoint: enabled
        UserData:
          Fn::Base64:
            Fn::Sub:
              - |
                #!/bin/bash
                set -ex
                exec > >(tee /var/log/user-data.log) 2>&1

                # Install dependencies (git is required, others for ephemeral storage setup)
                yum install -y git mdadm xfsprogs nvme-cli

                # Install smart-git-proxy RPM
                VERSION="${ProxyVersion}"
                RPM_URL="https://github.com/runs-on/smart-git-proxy/releases/download/v$VERSION/smart-git-proxy_${!VERSION}_linux_arm64.rpm"
                yum install -y "$RPM_URL"

                # Configure smart-git-proxy with Route53 for DNS registration
                echo "ROUTE53_HOSTED_ZONE_ID=${PrivateHostedZone}" >> /etc/smart-git-proxy/env
                echo "ROUTE53_RECORD_NAME=smart-git-proxy.runs-on.internal" >> /etc/smart-git-proxy/env

                # Restart service to pick up Route53 config
                systemctl restart smart-git-proxy

                # Wait for service to be healthy
                for i in {1..20}; do
                  curl -sf http://localhost:8080/healthz && break
                  echo "Waiting for healthz... ($i/20)"
                  sleep 1
                done
                curl -sf http://localhost:8080/healthz

                # Signal ASG that launch is complete
                /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}
              - ProxyVersion: !FindInMap [Config, Proxy, Version]

  # Auto Scaling Group
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref SubnetIds
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      HealthCheckType: EC2
      HealthCheckGracePeriod: 30
      LifecycleHookSpecificationList:
        - LifecycleTransition: autoscaling:EC2_INSTANCE_TERMINATING
          LifecycleHookName: DeregisterFromRoute53
          DefaultResult: CONTINUE
          HeartbeatTimeout: 60
      Tags:
        - Key: Name
          Value: smart-git-proxy
          PropagateAtLaunch: true
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT2M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 1
        PauseTime: PT2M
        WaitOnResourceSignals: true

  # Lambda to handle deregistration on termination
  DeregisterLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: Route53Deregister
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - route53:ChangeResourceRecordSets
                Resource: !Sub arn:aws:route53:::hostedzone/${PrivateHostedZone}
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:DeleteParameter
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/smart-git-proxy/instances/*
              - Effect: Allow
                Action:
                  - autoscaling:CompleteLifecycleAction
                Resource: '*'

  DeregisterLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-deregister-lambda
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt DeregisterLambdaRole.Arn
      Timeout: 30
      Code:
        ZipFile: |
          import boto3
          import json
          import os

          def handler(event, context):
              print(json.dumps(event))
              
              r53 = boto3.client('route53')
              ssm = boto3.client('ssm')
              asg = boto3.client('autoscaling')
              
              detail = event['detail']
              instance_id = detail['EC2InstanceId']
              lifecycle_hook = detail['LifecycleHookName']
              asg_name = detail['AutoScalingGroupName']
              
              param_name = f'/smart-git-proxy/instances/{instance_id}'
              
              try:
                  # Get instance data from SSM
                  response = ssm.get_parameter(Name=param_name)
                  data = json.loads(response['Parameter']['Value'])
                  
                  print(f"Deregistering {instance_id}: {data}")
                  
                  # Delete DNS record
                  r53.change_resource_record_sets(
                      HostedZoneId=data['hosted_zone_id'],
                      ChangeBatch={
                          'Comment': f'Deregister instance {instance_id}',
                          'Changes': [{
                              'Action': 'DELETE',
                              'ResourceRecordSet': {
                                  'Name': data['record_name'],
                                  'Type': 'A',
                                  'TTL': 10,
                                  'SetIdentifier': instance_id,
                                  'MultiValueAnswer': True,
                                  'ResourceRecords': [{'Value': data['private_ip']}]
                              }
                          }]
                      }
                  )
                  print(f"Deleted DNS record for {instance_id}")
                  
                  # Delete SSM parameter
                  ssm.delete_parameter(Name=param_name)
                  print(f"Deleted SSM parameter {param_name}")
                  
              except ssm.exceptions.ParameterNotFound:
                  print(f"SSM parameter not found for {instance_id}, skipping")
              except Exception as e:
                  print(f"Error during deregistration: {e}")
              
              # Always complete lifecycle action
              asg.complete_lifecycle_action(
                  LifecycleHookName=lifecycle_hook,
                  AutoScalingGroupName=asg_name,
                  InstanceId=instance_id,
                  LifecycleActionResult='CONTINUE'
              )
              
              return {'statusCode': 200}

  # EventBridge rule to trigger Lambda on termination
  TerminationRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.autoscaling
        detail-type:
          - EC2 Instance-terminate Lifecycle Action
        detail:
          AutoScalingGroupName:
            - !Ref AutoScalingGroup
      Targets:
        - Id: DeregisterLambda
          Arn: !GetAtt DeregisterLambda.Arn

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DeregisterLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt TerminationRule.Arn

Outputs:
  ProxyDnsName:
    Description: DNS name for the proxy
    Value: smart-git-proxy.runs-on.internal
  HostedZoneId:
    Description: Route53 private hosted zone ID
    Value: !Ref PrivateHostedZone
