AWSTemplateFormatVersion: '2010-09-09'
Description: Smart Git Proxy with auto-discovery via Cloud Map


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Main configuration [required]"
        Parameters:
          - VpcId
          - SubnetIds
          - ClientSecurityGroupId
          - InstanceType
          - RootVolumeSize
          - AmiId
          - ProxyVersion

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC to deploy into
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for the ASG (private subnets recommended)
  ClientSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group of clients that will access the proxy
  AssignPublicIp:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: Assign public IP (set to true for public subnets)
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type (use c5d/m5d/i3 for NVMe instance store)
  RootVolumeSize:
    Type: Number
    Default: 30
    Description: Root EBS volume size in GB
  AmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
  ProxyVersion:
    Type: String
    Default: latest
    Description: Version of smart-git-proxy to install (e.g., 0.1.0 or latest)

Conditions:
  UsePublicIp: !Equals [!Ref AssignPublicIp, "true"]

Resources:
  # Cloud Map namespace creates private hosted zone automatically
  ServiceNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: runs-on
      Vpc: !Ref VpcId
      Description: Private namespace for RunsOn services

  # Cloud Map service - this creates the DNS record
  ProxyService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: smart-git-proxy
      NamespaceId: !Ref ServiceNamespace
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 60
        RoutingPolicy: MULTIVALUE
      # Custom health check - instance reports its own health
      HealthCheckCustomConfig:
        FailureThreshold: 1

  # Security group for the proxy
  # Note: For SSM access in private subnets, ensure VPC has either:
  # - NAT Gateway, or
  # - VPC endpoints for: ssm, ssmmessages, ec2messages
  ProxySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Smart Git Proxy
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ClientSecurityGroupId
          Description: Git proxy from clients
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS for SSM, GitHub, package downloads
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP for package repos

  # IAM role for EC2 instances
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: CloudMapRegistration
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - servicediscovery:RegisterInstance
                  - servicediscovery:DeregisterInstance
                  - servicediscovery:UpdateInstanceCustomHealthStatus
                Resource: '*'
              - Effect: Allow
                Action:
                  - autoscaling:CompleteLifecycleAction
                Resource: '*'

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  # Launch template
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        IamInstanceProfile:
          Arn: !GetAtt InstanceProfile.Arn
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: !If [UsePublicIp, true, false]
            Groups:
              - !Ref ProxySecurityGroup
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: !Ref RootVolumeSize
              VolumeType: gp3
              DeleteOnTermination: true
        MetadataOptions:
          HttpTokens: required
          HttpEndpoint: enabled
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -ex
            exec > >(tee /var/log/user-data.log) 2>&1

            # Install dependencies for ephemeral storage setup (preinstall script needs these)
            yum install -y mdadm xfsprogs nvme-cli

            # Install smart-git-proxy RPM
            VERSION="${ProxyVersion}"
            if [ "$VERSION" = "latest" ]; then
              RPM_URL=$(curl -s https://api.github.com/repos/runs-on/smart-git-proxy/releases/latest | grep browser_download_url | grep "linux_amd64.rpm" | cut -d '"' -f 4)
            else
              RPM_URL="https://github.com/runs-on/smart-git-proxy/releases/download/v$VERSION/smart-git-proxy_${!VERSION}_linux_amd64.rpm"
            fi
            
            yum install -y "$RPM_URL"

            # Configure smart-git-proxy with Cloud Map service ID for registration and health heartbeat
            echo "AWS_CLOUD_MAP_SERVICE_ID=${ProxyService}" >> /etc/smart-git-proxy/env

            # Restart service to pick up Cloud Map config
            systemctl restart smart-git-proxy

            # Wait for service to register and become healthy
            sleep 5

            # Signal ASG that launch is complete
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}

  # Auto Scaling Group
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref SubnetIds
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 1
      DesiredCapacity: 1
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      LifecycleHookSpecificationList:
        - LifecycleTransition: autoscaling:EC2_INSTANCE_TERMINATING
          LifecycleHookName: DeregisterFromCloudMap
          DefaultResult: CONTINUE
          HeartbeatTimeout: 60
      Tags:
        - Key: Name
          Value: smart-git-proxy
          PropagateAtLaunch: true
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT5M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 0
        MaxBatchSize: 1
        PauseTime: PT5M
        WaitOnResourceSignals: true

  # Lambda to handle deregistration on termination
  DeregisterLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CloudMapDeregister
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - servicediscovery:DeregisterInstance
                Resource: '*'
              - Effect: Allow
                Action:
                  - autoscaling:CompleteLifecycleAction
                Resource: '*'

  DeregisterLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-deregister
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt DeregisterLambdaRole.Arn
      Timeout: 30
      Environment:
        Variables:
          SERVICE_ID: !Ref ProxyService
      Code:
        ZipFile: |
          import boto3
          import os
          import json

          def handler(event, context):
              print(json.dumps(event))
              
              sd = boto3.client('servicediscovery')
              asg = boto3.client('autoscaling')
              
              service_id = os.environ['SERVICE_ID']
              detail = event['detail']
              instance_id = detail['EC2InstanceId']
              lifecycle_hook = detail['LifecycleHookName']
              asg_name = detail['AutoScalingGroupName']
              
              try:
                  sd.deregister_instance(ServiceId=service_id, InstanceId=instance_id)
                  print(f"Deregistered {instance_id}")
              except Exception as e:
                  print(f"Error: {e}")
              
              asg.complete_lifecycle_action(
                  LifecycleHookName=lifecycle_hook,
                  AutoScalingGroupName=asg_name,
                  InstanceId=instance_id,
                  LifecycleActionResult='CONTINUE'
              )
              return {'statusCode': 200}

  # EventBridge rule to trigger Lambda on termination
  TerminationRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.autoscaling
        detail-type:
          - EC2 Instance-terminate Lifecycle Action
        detail:
          AutoScalingGroupName:
            - !Ref AutoScalingGroup
      Targets:
        - Id: DeregisterLambda
          Arn: !GetAtt DeregisterLambda.Arn

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DeregisterLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt TerminationRule.Arn

Outputs:
  ProxyDnsName:
    Description: DNS name for the proxy
    Value: smart-git-proxy.runs-on
  NamespaceId:
    Description: Cloud Map namespace ID
    Value: !Ref ServiceNamespace
  ServiceId:
    Description: Cloud Map service ID
    Value: !Ref ProxyService
